#!/usr/bin/env python3
"""
My-OS Calendar Integration Engine
Parses extracted tasks and schedules them into Google Calendar via Google API or iCal feed.
"""

import os
import sys
import yaml
import datetime

def load_config():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    config_path = os.path.join(script_dir, "..", "config", "config.yaml")
    config = {}
    if os.path.exists(config_path):
        with open(config_path, "r", encoding="utf-8") as f:
            config = yaml.safe_load(f) or {}
    return config

def create_ics_event(title, start_datetime, duration_minutes=30, description=""):
    end_datetime = start_datetime + datetime.timedelta(minutes=duration_minutes)
    
    fmt = "%Y%m%dT%H%M%SZ"
    start_str = start_datetime.strftime(fmt)
    end_str = end_datetime.strftime(fmt)
    
    ics_content = f"""BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//My-OS Personal OS//Calendar Sync//EN
BEGIN:VEVENT
SUMMARY:{title}
DESCRIPTION:{description}
DTSTART:{start_str}
DTEND:{end_str}
STATUS:CONFIRMED
END:VEVENT
END:VCALENDAR"""
    return ics_content

def main():
    print("==================================================")
    print("        MY-OS CALENDAR INTEGRATION               ")
    print("==================================================")
    
    if len(sys.argv) < 2:
        print("Usage: python calendar_sync.py \"Task Title\" [YYYY-MM-DD HH:MM] [Duration Mins]")
        print("Example: python calendar_sync.py \"Draft LinkedIn Post on Ownership\" \"2026-08-03 10:00\" 45")
        return
        
    title = sys.argv[1]
    time_str = sys.argv[2] if len(sys.argv) > 2 else datetime.datetime.now().strftime("%Y-%m-%d 10:00")
    duration = int(sys.argv[3]) if len(sys.argv) > 3 else 30
    
    try:
        start_dt = datetime.datetime.strptime(time_str, "%Y-%m-%d %H:%M")
    except Exception:
        start_dt = datetime.datetime.now() + datetime.timedelta(days=1)
        
    ics_data = create_ics_event(title, start_dt, duration, "Generated by My-OS Task Scheduler")
    
    output_dir = os.path.join(os.path.dirname(__file__), "..", "..", "system", "calendar")
    os.makedirs(output_dir, exist_ok=True)
    filename = f"event-{start_dt.strftime('%Y%m%d-%H%M')}.ics"
    filepath = os.path.join(output_dir, filename)
    
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(ics_data)
        
    print(f"\n[Calendar] Created event file: {filepath}")
    print(f"Title: {title}")
    print(f"Date : {start_dt.strftime('%Y-%m-%d %H:%M')}")
    print("\nTip: Double click the .ics file to instantly add it to Google Calendar / Outlook / Apple Calendar!")

if __name__ == "__main__":
    main()
